workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16
        DEVELOPMENT_TEAM: YOUR_TEAM_ID # Sostituisci con il tuo Team ID Apple (puoi anche ometterlo)
    scripts:
      - name: Install Node.js
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          source ~/.nvm/nvm.sh
          nvm install $NODE_VERSION
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Web Assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS App (without signing)
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -archivePath ios/App/build/App.xcarchive \
                     -sdk iphoneos \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_ALLOWED=NO \
                     archive
      - name: Export iOS App to IPA (without signing)
        script: |
            # Esegui la costruzione dell'IPA senza firma
            xcodebuild -workspace ios/App/App.xcworkspace \
                      -scheme App \
                      -archivePath ios/App/build/App.xcarchive \
                      -sdk iphoneos \
                      CODE_SIGNING_REQUIRED=NO \
                      CODE_SIGN_IDENTITY="" \
                      CODE_SIGNING_ALLOWED=NO \
                      archive

            # Esporta l'IPA senza firma, senza teamID
            xcodebuild -exportArchive \
                      -archivePath ios/App/build/App.xcarchive \
                      -exportOptionsPlist exportOptions.plist \
                      -exportPath $CM_BUILD_DIR/ipa \
                      CODE_SIGNING_REQUIRED=NO \
                      CODE_SIGNING_ALLOWED=NO
