workflows:
  ios:
    name: iOS Build
    max_build_duration: 60 # durata massima per la build (in minuti)
    environment:
      flutter: stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npx cap sync ios
      - run:
          name: Build iOS App
          command: |
            npx cap build ios --prod --release
      - upload-artifact:
          path: ios/App/build/ios/iphoneos/*.ipa
