workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npx cap sync ios
      - run:
          name: Build iOS app
          command: |
            npx cap build ios --prod --release
      - upload-artifact:
          name: iOS app
          path: ios/App/build/ios/iphoneos/*.ipa
