workflows:
  ios:
    name: iOS Build
    max_build_duration: 60 # durata massima per la build (in minuti)
    environment:
      vars:
        NODE_VERSION: 16 # Specifica la versione di Node.js
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npx cap sync ios
      - name: Build iOS App
        script: |
          npx cap build ios --prod --release
